main: x.Entt.ClansX.CX
version: 1.1.5
name: ClansX
author: Enttbot
api-version: "1.13"
softdepend: [Vault, PlaceholderAPI]

commands:
  clansx:
    description: The main command to config and manage CX. Only for admins!
    aliases: [clx]
  clans:
    description: The command for clans (creating, deleting, etc). For users
    aliases: [cls]
  cxstats:
    description: The command for see the player stats of ClansX.
    aliases: [cxs]

permissions:
  cx.*:
    description: Get all perms of the plugin.
    default: op
    children:
      cx.admin: true
      cx.user: true
  cx.admin:
    default: op
    description: Get access to admin commands.
  cx.user:
    default: true
    description: Get access to user commands.